/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emisor;

import conexion.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import javax.swing.text.StyledEditorKit;
import login.login_window;
import validacion.Validacion;

/**
 *
 * @author ar275
 */
public class AltaEmisor extends javax.swing.JFrame {

    /**
     * Creates new form alta_emisor
     */
    conexion cx = new conexion();//conexion a la base de datos
    Validacion valida = new Validacion();
    Image menu_img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/menu_icon.png"));
    //Imagen x del menu
    Image equis_icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/menu_iconx.png"));
    Image logo_img= Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/file.png"));

    public AltaEmisor() {
        initComponents();
        btn_menu.setIcon(new ImageIcon(menu_img.getScaledInstance( btn_menu.getWidth(),btn_menu.getHeight(), Image.SCALE_SMOOTH)));
        logo_nav.setIcon(new ImageIcon(logo_img.getScaledInstance(logo_nav.getWidth(), logo_nav.getHeight(), Image.SCALE_SMOOTH)));
        menu_salir.setVisible(false);
//        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize(this.getSize().width,screenSize.height);
        this.setLocationRelativeTo(null);//La ventana aparece en el centro
        this.setLocation(this.getLocation().x,0);
        
        // Formatear la fecha en el formato "dd/MM/yyyy"
        LocalDate fechaActual = LocalDate.now();
        // Crear un formato con localización en español
        DateTimeFormatter formatoEspanol = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy", new Locale("es", "ES"));
        // Formatear la fecha en español
        String fechaFormateada = fechaActual.format(formatoEspanol);
        Fecha.setText(fechaFormateada);//Mostar hora
        //Mostrar la hora en tiempo real
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener la hora actual
                LocalTime horaActual = LocalTime.now();
                // Formatear la hora en el formato "HH:mm:ss"
                DateTimeFormatter formatoHora = DateTimeFormatter.ofPattern("hh:mm:ss a");
                String horaFormateada = horaActual.format(formatoHora);
                // Actualizar el JLabel con la hora actual
                hora_lb.setText(horaFormateada);
            }
        });
        timer.start();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barra_nav = new javax.swing.JPanel();
        Fecha = new javax.swing.JLabel();
        hora_lb = new javax.swing.JLabel();
        btn_menu = new javax.swing.JLabel();
        logo_nav = new javax.swing.JLabel();
        entrada_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        datosfiscales_titulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        datosPersonales_titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        registrarEmisor_Titulo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombres_lb = new javax.swing.JLabel();
        entrada_nombres = new javax.swing.JTextField();
        entrada_apellidoPaterno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        entrada_apellidoMaterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        entrada_correoElectronico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        entrada_rfc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        entrada_regimen = new javax.swing.JComboBox<>();
        entrada_cp = new javax.swing.JFormattedTextField();
        menu_salir = new javax.swing.JPanel();
        btn_salir = new javax.swing.JPanel();
        icon_salir = new javax.swing.JLabel();
        text_salir = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btn_cerrarSesion = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_guardarDatos = new paneles.PanelRound();
        contenero_btn = new paneles.PanelRound();
        text_guardarDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Instituto Manuel Andres Lopez Obrador - Alta Emisor");
        setMinimumSize(new java.awt.Dimension(912, 600));

        fondo.setBackground(new java.awt.Color(240, 240, 240));
        fondo.setPreferredSize(new java.awt.Dimension(1043, 610));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_nav.setBackground(new java.awt.Color(198, 54, 55));
        barra_nav.setName("instituo Manuel Andres Lopez Obrador - Login"); // NOI18N
        barra_nav.setPreferredSize(new java.awt.Dimension(0, 70));
        barra_nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fecha.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("Fecha: ");
        barra_nav.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, -1));

        hora_lb.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        hora_lb.setForeground(new java.awt.Color(255, 255, 255));
        hora_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hora_lb.setText("Hora: ");
        barra_nav.add(hora_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, -1));

        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_icon.png"))); // NOI18N
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
        });
        barra_nav.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 50, 40));
        barra_nav.add(logo_nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 80, 80));

        fondo.add(barra_nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1043, 80));

        entrada_fechaNacimiento.setDateFormatString("dd MMM y");
        fondo.add(entrada_fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 426, 190, -1));

        datosfiscales_titulo.setBackground(new java.awt.Color(255, 255, 255));
        datosfiscales_titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Teko", 1, 24)); // NOI18N
        jLabel3.setText("Datos fiscales");
        datosfiscales_titulo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 30));

        fondo.add(datosfiscales_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 170, -1));

        datosPersonales_titulo.setBackground(new java.awt.Color(255, 255, 255));
        datosPersonales_titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Teko", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos personales");
        datosPersonales_titulo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        fondo.add(datosPersonales_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 180, 200, -1));

        registrarEmisor_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        registrarEmisor_Titulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Teko", 1, 48)); // NOI18N
        jLabel4.setText("Registrar emisor");
        registrarEmisor_Titulo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 60));

        fondo.add(registrarEmisor_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 610, 60));

        nombres_lb.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        nombres_lb.setLabelFor(entrada_nombres);
        nombres_lb.setText("Nombre (s)");
        fondo.add(nombres_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 110, -1));
        fondo.add(entrada_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 237, 190, -1));
        fondo.add(entrada_apellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 302, 190, -1));

        jLabel2.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel2.setText("Apellido peterno");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 305, 130, -1));

        jLabel5.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel5.setText("Apellido Materno");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 367, 130, -1));
        fondo.add(entrada_apellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 364, 190, -1));

        jLabel6.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel6.setText("Fecha de nacimiento");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 180, 20));

        jLabel7.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel7.setText("Correo electronico");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 170, 20));
        fondo.add(entrada_correoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 190, -1));

        jLabel8.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel8.setText("RFC");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));
        fondo.add(entrada_rfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 157, -1));

        jLabel9.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel9.setText("Regimen Fiscal");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel10.setText("Código postal");
        fondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 120, -1));

        entrada_regimen.setFont(new java.awt.Font("Teko", 1, 14)); // NOI18N
        entrada_regimen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simplificado de Confianza. ", "612  Persona Física con Actividad Empresarial", "605  Sueldos y Salarios e Ingresos Asimilados a Salarios" }));
        entrada_regimen.setSelectedIndex(1);
        fondo.add(entrada_regimen, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 350, 30));

        try {
            entrada_cp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fondo.add(entrada_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 160, 30));

        menu_salir.setBackground(new java.awt.Color(169, 30, 31));
        menu_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_salir.setBackground(new java.awt.Color(169, 30, 31));
        btn_salir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });
        btn_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salir.png"))); // NOI18N
        btn_salir.add(icon_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        text_salir.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        text_salir.setForeground(new java.awt.Color(255, 255, 255));
        text_salir.setText("Salir");
        btn_salir.add(text_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 60, 50));
        btn_salir.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 140, 10));

        menu_salir.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        btn_cerrarSesion.setBackground(new java.awt.Color(169, 30, 31));
        btn_cerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarSesionMouseClicked(evt);
            }
        });
        btn_cerrarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cerrar sesión");
        btn_cerrarSesion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cerrarSesion.png"))); // NOI18N
        btn_cerrarSesion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));
        btn_cerrarSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 10));
        btn_cerrarSesion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 140, 10));

        menu_salir.add(btn_cerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 70, 150, 50));
        menu_salir.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 60, 140, 10));

        fondo.add(menu_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 190, 130));

        btn_guardarDatos.setBackground(new java.awt.Color(0, 0, 0));
        btn_guardarDatos.setRoundBottomLeft(10);
        btn_guardarDatos.setRoundBottomRight(10);
        btn_guardarDatos.setRoundTopLeft(10);
        btn_guardarDatos.setRoundTopRight(10);
        btn_guardarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarDatosMouseClicked(evt);
            }
        });
        btn_guardarDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenero_btn.setBackground(new java.awt.Color(217, 217, 217));
        contenero_btn.setRoundBottomLeft(10);
        contenero_btn.setRoundBottomRight(10);
        contenero_btn.setRoundTopLeft(10);
        contenero_btn.setRoundTopRight(10);
        contenero_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_guardarDatos.setFont(new java.awt.Font("Teko", 1, 18)); // NOI18N
        text_guardarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_guardarDatos.setText("Guardar datos del emisor");
        text_guardarDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contenero_btn.add(text_guardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 40));

        btn_guardarDatos.add(contenero_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 2, 240, 40));

        fondo.add(btn_guardarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 245, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
//    public boolean camposVcaios(){//Funcion que valida que ningun campo este vacio
//        return entrada_nombres.getText().isEmpty() && entrada_apellidoPaterno.getText().isEmpty()
//                && entrada_apellidoMaterno.getText().isEmpty() && entrada_fechaNacimiento.getDate()==null
//                && entrada_correoElectronico.getText().isEmpty() && entrada_rfc.getText().isEmpty()
//                && entrada_cp.getText().isEmpty();
//    }
   
    
    public boolean fechaValida(){
        return entrada_fechaNacimiento.getDate() != null;
    }

    public boolean rfc_existente(){
        try {
            //Prepara la consulta para verificar si existe el RFC
            String consulta_rfc = "SELECT * FROM emisor WHERE rfc = ?";
            PreparedStatement ps = cx.conectar().prepareStatement(consulta_rfc);
            ps.setString(1, entrada_rfc.getText());
            ResultSet rs = ps.executeQuery();
            if(rs.next()){//si encuentra un fila con el RFC quiere decir que ya existe
                return true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(AltaEmisor.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;//Retorna falso si no encuentra el RFC
    }
    
    //Funcion para validar el RFC
    public boolean rfc_valido() {
        if (entrada_rfc.getText().length() != 13) {
            JOptionPane.showMessageDialog(null, "El tamaño del RFC es de 13 caracteres obligatoriamnete", "RFC no valido", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        //obtener la homoclave del RFC ingresado
        String rfc_user = entrada_rfc.getText().toUpperCase();
        String homoclave = "";
        homoclave += entrada_rfc.getText().toUpperCase().charAt(10);
        homoclave += entrada_rfc.getText().toUpperCase().charAt(11);
        homoclave += entrada_rfc.getText().toUpperCase().charAt(12);

        // Obtener el objeto Date desde el JDateChooser
        Date fechaNacimiento = entrada_fechaNacimiento.getDate();

        // Crear una instancia de Calendar y asignarle la fecha
        Calendar calendarFechaNacimiento = Calendar.getInstance();
        calendarFechaNacimiento.setTime(fechaNacimiento);

        // Llamar al método creando la RFC
        String rfc_sistema = valida.crear_rfc(
                entrada_nombres.getText(),
                entrada_apellidoPaterno.getText(),
                entrada_apellidoMaterno.getText(),
                calendarFechaNacimiento, // Pasa el objeto Calendar aquí
                homoclave
        );
        
        if (rfc_user.equals(rfc_sistema)){
            //Expresion para validar un RFC
            String regex = "^[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3}$";
            // Compilar la expresión regular en un patrón
            Pattern pattern = Pattern.compile(regex);
            // Crear el matcher que validará el RFC
            Matcher matcher = pattern.matcher(rfc_user);
            // Retornar si coincide o no
            return matcher.matches();
        }
        JOptionPane.showMessageDialog(null,"El RFC no coincide con el nombre, apellidos o con la fecha de nacimiento del emisor", "RFC no valido", JOptionPane.WARNING_MESSAGE);
        return false;
    }
    public void altaEmisor() {
        try {
            int cp = Integer.parseInt(entrada_cp.getText());
            //Obtener todos los datos de entrada
            Date fecha_nacimiento = entrada_fechaNacimiento.getDate();
            java.sql.Date fecha_sql = new java.sql.Date(fecha_nacimiento.getTime());
            //Crear conexion a la base de datos
            //Preparar consulta para insertar los datos
            String query_alta = "INSERT INTO emisor "
                    + "(rfc, nombres, apellido_paterno, apellido_materno, fecha_nacimiento, correo_electronico, domiciolio_fiscal, regimen)"
                    + "VALUES (?,?,?,?,?,?,?,?)";
            PreparedStatement ps = cx.conectar().prepareStatement(query_alta);//Creacion de la consulta
            ps.setString(1, entrada_rfc.getText());
            ps.setString(2, entrada_nombres.getText());
            ps.setString(3, entrada_apellidoPaterno.getText());
            ps.setString(4, entrada_apellidoMaterno.getText());
            ps.setDate(5, fecha_sql);
            ps.setString(6, entrada_correoElectronico.getText());
            ps.setInt(7, cp);
            ps.setString(8, entrada_regimen.getSelectedItem().toString());
            
            //Verifica que se realizó el registro
            int filas_insertadas = ps.executeUpdate();
            if(filas_insertadas >0){
                 JOptionPane.showMessageDialog(null,"Datos registrados exitosamente", "Registro existoso", JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(null,"Hubo un error al registrar los datos, intente otra vez", "Error en el registro", JOptionPane.WARNING_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Hubo un error al registrar los datos, intente otra vez", "Error en el registro", JOptionPane.WARNING_MESSAGE);;
        }
    }
    
    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {//click izquierdo
            if(menu_salir.isVisible()){
                menu_salir.setVisible(false);
                btn_menu.setIcon(new ImageIcon(menu_img.getScaledInstance( btn_menu.getWidth(),btn_menu.getHeight(), Image.SCALE_SMOOTH)));
                
            }else{
                menu_salir.setVisible(true);
                btn_menu.setIcon(new ImageIcon(equis_icon.getScaledInstance( btn_menu.getWidth(),btn_menu.getHeight(), Image.SCALE_SMOOTH)));
            }
        }
    }//GEN-LAST:event_btn_menuMouseClicked

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        Object[] opciones = {"Aceptar", "Cancelar"};
        if (SwingUtilities.isLeftMouseButton(evt)) {//click izquierdo
            //dialogo que pregunta si desea confirmar salir
            int opcionSeleccionada = JOptionPane.showOptionDialog(null,
                    "¿Cerrar sesión y salir?", "Confirmación de salida", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, opciones, opciones[1]); // Por defecto, la opción seleccionada es "Cancelar"
            // Manejar las opciones seleccionadas
            if (opcionSeleccionada == JOptionPane.YES_OPTION) {
                System.exit(0); // Salir del programa
            } else {
                return;
            }
        }
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarSesionMouseClicked
        Object[] opciones = {"Aceptar", "Cancelar"};
        if (SwingUtilities.isLeftMouseButton(evt)) {//click izquierdo
            //dialogo que pregunta si desea confirmar salir
            int opcionSeleccionada = JOptionPane.showOptionDialog(null,
                    "¿Cerrar sesión?", "Confirmación de cerrar sesión", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE,
                    null, opciones, opciones[1]); // Por defecto, la opción seleccionada es "Cancelar"
            // Manejar las opciones seleccionadas
            if (opcionSeleccionada == JOptionPane.YES_OPTION) {
                login_window ventana = new login_window();
                ventana.setVisible(true);
                this.setVisible(false);
            } else {
                return;
            }
        }
    }//GEN-LAST:event_btn_cerrarSesionMouseClicked

    private void btn_guardarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarDatosMouseClicked
         if (SwingUtilities.isLeftMouseButton(evt)) {//click izquierdo
            if(!valida.nombresValidos(entrada_nombres.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un nombre valido", "Nombre no valido", JOptionPane.WARNING_MESSAGE);
                entrada_nombres.requestFocusInWindow();
                return;
            }
            if(!valida.apellidoValido(entrada_apellidoPaterno.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un apellido paterno valido", "Apellido no valido", JOptionPane.WARNING_MESSAGE);
                entrada_apellidoPaterno.requestFocusInWindow();
                return;
            }
            if(!valida.apellidoValido(entrada_apellidoMaterno.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un apellido materno valido", "Apellido no valido", JOptionPane.WARNING_MESSAGE);
                entrada_apellidoMaterno.requestFocusInWindow();
                return;
            }
            if(!fechaValida()){
                JOptionPane.showMessageDialog(null, "Ingrese una fecha de nacimiento valida", "Fecha no valido", JOptionPane.WARNING_MESSAGE);
               entrada_fechaNacimiento.requestFocusInWindow();
                return;
            }
            if(!valida.correo_valido(entrada_correoElectronico.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un correo electronico valido", "Correo no valido", JOptionPane.WARNING_MESSAGE);
                entrada_correoElectronico.requestFocusInWindow();
                return;
            }
             if(!rfc_valido()){
                entrada_rfc.requestFocusInWindow();
                return;
            }
            if(rfc_existente()){
                JOptionPane.showMessageDialog(null, "El RFC ya se encuentra registrado", "RFC existente", JOptionPane.WARNING_MESSAGE);
                entrada_rfc.requestFocusInWindow();    // Borde al tener foco;
                return;
            }
            if(!valida.cpValido(entrada_cp.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese un codigo postal valido", "Codigo postal no valido", JOptionPane.WARNING_MESSAGE);
                entrada_cp.requestFocusInWindow();    // Borde al tener foco;
                return;
            }
            //altaEmisor();
            System.out.println("Muy bien");
        }
    }//GEN-LAST:event_btn_guardarDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaEmisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel barra_nav;
    private javax.swing.JPanel btn_cerrarSesion;
    private paneles.PanelRound btn_guardarDatos;
    private javax.swing.JLabel btn_menu;
    private javax.swing.JPanel btn_salir;
    private paneles.PanelRound contenero_btn;
    private javax.swing.JPanel datosPersonales_titulo;
    private javax.swing.JPanel datosfiscales_titulo;
    private javax.swing.JTextField entrada_apellidoMaterno;
    private javax.swing.JTextField entrada_apellidoPaterno;
    private javax.swing.JTextField entrada_correoElectronico;
    private javax.swing.JFormattedTextField entrada_cp;
    private com.toedter.calendar.JDateChooser entrada_fechaNacimiento;
    private javax.swing.JTextField entrada_nombres;
    private javax.swing.JComboBox<String> entrada_regimen;
    private javax.swing.JTextField entrada_rfc;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel hora_lb;
    private javax.swing.JLabel icon_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel logo_nav;
    private javax.swing.JPanel menu_salir;
    private javax.swing.JLabel nombres_lb;
    private javax.swing.JPanel registrarEmisor_Titulo;
    private javax.swing.JLabel text_guardarDatos;
    private javax.swing.JLabel text_salir;
    // End of variables declaration//GEN-END:variables
}
