/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emisor;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author ar275
 */
public class PrimerInicio extends javax.swing.JFrame {

    /**
     * Creates new form PrimerInicio
     */
    public PrimerInicio() {
        initComponents();
        //Personalizar el tamaño del logo
        Image logo_img= Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logo_escuela.png"));
        logo_lb.setIcon(new ImageIcon(logo_img.getScaledInstance(logo_lb.getWidth(), logo_lb.getHeight(), Image.SCALE_SMOOTH)));
        //Mostrar ventana en el centro
        this.setLocationRelativeTo(null);//La ventana aparece en el centro
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barra_nav = new javax.swing.JPanel();
        Fecha = new javax.swing.JLabel();
        hora_lb = new javax.swing.JLabel();
        text_bienvenida1 = new javax.swing.JLabel();
        text_bienvenida2 = new javax.swing.JLabel();
        text_bienvenida3 = new javax.swing.JLabel();
        logo_lb = new javax.swing.JLabel();
        msj_text1 = new javax.swing.JLabel();
        mjs_text2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JPanel();
        icon_salirlb = new javax.swing.JLabel();
        text_salir = new javax.swing.JLabel();
        btn_continuar = new javax.swing.JPanel();
        text_continuar = new javax.swing.JLabel();
        icon_continuar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(924, 600));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra_nav.setBackground(new java.awt.Color(198, 54, 55));
        barra_nav.setName("instituo Manuel Andres Lopez Obrador - Login"); // NOI18N
        barra_nav.setPreferredSize(new java.awt.Dimension(0, 70));
        barra_nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setText("Fecha: ");
        barra_nav.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, -1));

        hora_lb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hora_lb.setForeground(new java.awt.Color(255, 255, 255));
        hora_lb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hora_lb.setText("Hora: ");
        barra_nav.add(hora_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 110, -1));

        fondo.add(barra_nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 912, -1));

        text_bienvenida1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        text_bienvenida1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bienvenida1.setText("TE DAMOS LA BIENVENIDA AL SISTEMA");
        fondo.add(text_bienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        text_bienvenida2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        text_bienvenida2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bienvenida2.setText("DE FACTURACIÓN DEL");
        fondo.add(text_bienvenida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        text_bienvenida3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text_bienvenida3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_bienvenida3.setText("\"INSTITUTO MANUEL ANDRÉS LÓPEZ OBRADOR\"");
        fondo.add(text_bienvenida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        logo_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_escuela.png"))); // NOI18N
        logo_lb.setText("jLabel2");
        logo_lb.setMaximumSize(new java.awt.Dimension(400, 400));
        logo_lb.setMinimumSize(new java.awt.Dimension(400, 400));
        logo_lb.setPreferredSize(new java.awt.Dimension(400, 600));
        fondo.add(logo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 320, 240));

        msj_text1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        msj_text1.setText("persona que emitirá las facturas, como el dueño del colegio, etc.");
        fondo.add(msj_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 840, 30));

        mjs_text2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mjs_text2.setText("Antes de comenzar a generar facturas, necesitas registrar los datos de la");
        fondo.add(mjs_text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 840, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("IMPORTANTE: ");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        btn_salir.setBackground(new java.awt.Color(198, 54, 55));
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_salirMouseClicked(evt);
            }
        });
        btn_salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_salirlb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_salir.png"))); // NOI18N
        btn_salir.add(icon_salirlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, -1));

        text_salir.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        text_salir.setForeground(new java.awt.Color(255, 255, 255));
        text_salir.setText("SALIR");
        btn_salir.add(text_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 30));

        fondo.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 180, 50));

        btn_continuar.setBackground(new java.awt.Color(198, 54, 55));
        btn_continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_continuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_continuarMouseClicked(evt);
            }
        });
        btn_continuar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_continuar.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        text_continuar.setForeground(new java.awt.Color(255, 255, 255));
        text_continuar.setText("CONTINUAR");
        btn_continuar.add(text_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        icon_continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_continuar.png"))); // NOI18N
        btn_continuar.add(icon_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 40, -1));

        fondo.add(btn_continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 530, 180, 50));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_salirMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            System.out.println("Se hizo clic con el boton izquierdo.");
        }
    }//GEN-LAST:event_btn_salirMouseClicked

    private void btn_continuarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_continuarMouseClicked
        if (SwingUtilities.isLeftMouseButton(evt)) {
            System.out.println("Se hizo clic con el boton izquierdo.");
        }
    }//GEN-LAST:event_btn_continuarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimerInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimerInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel barra_nav;
    private javax.swing.JPanel btn_continuar;
    private javax.swing.JPanel btn_salir;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel hora_lb;
    private javax.swing.JLabel icon_continuar;
    private javax.swing.JLabel icon_salirlb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel logo_lb;
    private javax.swing.JLabel mjs_text2;
    private javax.swing.JLabel msj_text1;
    private javax.swing.JLabel text_bienvenida1;
    private javax.swing.JLabel text_bienvenida2;
    private javax.swing.JLabel text_bienvenida3;
    private javax.swing.JLabel text_continuar;
    private javax.swing.JLabel text_salir;
    // End of variables declaration//GEN-END:variables
}
