/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package facturacion;

import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JDialog;

/**
 *
 * @author ar275
 */
public class ModeloFactura extends JDialog {

    /**
     * Creates new form ModeloFactura
     */
    public ModeloFactura(Frame FramePadre, boolean modal) {
        super(FramePadre, modal);  // Establece la ventana como modal
        // Establece el comportamiento de cierre adecuado
        initComponents();

        //Personalizar el tamaño del logo
        Image logo_img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("../img/logo_escuela.png"));
        logo_lb.setIcon(new ImageIcon(logo_img.getScaledInstance(logo_lb.getWidth(), logo_lb.getHeight(), Image.SCALE_SMOOTH)));
        
        //etiqueta para el rfc del emisor
        rfc_emisor.setText("<html>Régimen fiscal: 612 personas físicas con actividades empresariales y profesionales</html>");
        
        //regimen padre
        regimen_padre.setText("<html>612 Personas Físicas con Actividades Empresariales y Profesionales </html>");
        
        //aparece en el centro de la pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logo_lb = new javax.swing.JLabel();
        nombre_escuela = new javax.swing.JLabel();
        nombre_escuela1 = new javax.swing.JLabel();
        nombre_emisor = new javax.swing.JLabel();
        rfc_emisor1 = new javax.swing.JLabel();
        rfc_emisor = new javax.swing.JLabel();
        fechaHoraEmision = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        no_factura = new javax.swing.JLabel();
        titulo_fechaHoraEmision1 = new javax.swing.JTextField();
        fechaHoraEmison = new javax.swing.JTextField();
        titulo_fechaHoraCertificacion = new javax.swing.JTextField();
        titulo_codigoPostalExped1 = new javax.swing.JTextField();
        cp_Expedicion1 = new javax.swing.JTextField();
        encabezado_Receptor = new paneles.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        encabezado_datosFiscales = new paneles.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        contenedor_receptor = new paneles.PanelRound();
        nombre_padre = new javax.swing.JLabel();
        Tituloregimen_padre = new javax.swing.JLabel();
        domicilio_fiscalPadre = new javax.swing.JLabel();
        rfc_padre1 = new javax.swing.JLabel();
        titulo_cfdi1 = new javax.swing.JLabel();
        titulo_cp2 = new javax.swing.JLabel();
        regimen_padre = new javax.swing.JLabel();
        titulo_rfc2 = new javax.swing.JLabel();
        uso_CFDI2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        contenedor_datosFiscales = new paneles.PanelRound();
        titulo_certificadoEmisor = new javax.swing.JLabel();
        certificadoSAT = new javax.swing.JLabel();
        titulo_exportación = new javax.swing.JLabel();
        folioSat = new javax.swing.JLabel();
        titulo_certificadoEmisor1 = new javax.swing.JLabel();
        exportacion = new javax.swing.JLabel();
        titulo_FolioSat2 = new javax.swing.JLabel();
        titulo_leyenda = new javax.swing.JLabel();
        certificadoEmisor2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instituto Manuel Andres Lopez Obrador - Factura previa");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2147483647, 700));
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(1100, 740));
        setResizable(false);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 1100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_lb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_escuela.png"))); // NOI18N
        logo_lb.setText("jLabel2");
        logo_lb.setMaximumSize(new java.awt.Dimension(400, 400));
        logo_lb.setMinimumSize(new java.awt.Dimension(400, 400));
        logo_lb.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.add(logo_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, 120));

        nombre_escuela.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombre_escuela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_escuela.setText("López Obrador");
        jPanel1.add(nombre_escuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 130, -1));

        nombre_escuela1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombre_escuela1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_escuela1.setText("Andrés Manuel");
        jPanel1.add(nombre_escuela1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 130, -1));

        nombre_emisor.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        nombre_emisor.setText("Carolina Astudillo Hernández");
        jPanel1.add(nombre_emisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 240, 30));

        rfc_emisor1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rfc_emisor1.setText("RFC: AUHC670504FFF");
        jPanel1.add(rfc_emisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 180, 30));

        rfc_emisor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        rfc_emisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rfc_emisor.setText("Regimen emisor");
        jPanel1.add(rfc_emisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 420, 40));

        fechaHoraEmision.setEditable(false);
        fechaHoraEmision.setBackground(new java.awt.Color(255, 255, 255));
        fechaHoraEmision.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        fechaHoraEmision.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fechaHoraEmision.setText("  Fecha y hora de emisión");
        fechaHoraEmision.setBorder(null);
        fechaHoraEmision.setFocusable(false);
        jPanel1.add(fechaHoraEmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 260, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(198, 54, 55));
        jLabel2.setText("Factura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 70, 20));

        no_factura.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        no_factura.setForeground(new java.awt.Color(198, 54, 55));
        no_factura.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        no_factura.setText("jLabel3");
        jPanel1.add(no_factura, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 190, 20));

        titulo_fechaHoraEmision1.setEditable(false);
        titulo_fechaHoraEmision1.setBackground(new java.awt.Color(198, 54, 55));
        titulo_fechaHoraEmision1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_fechaHoraEmision1.setForeground(new java.awt.Color(255, 255, 255));
        titulo_fechaHoraEmision1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        titulo_fechaHoraEmision1.setText("  Fecha y hora de emisión");
        titulo_fechaHoraEmision1.setBorder(null);
        titulo_fechaHoraEmision1.setFocusable(false);
        jPanel1.add(titulo_fechaHoraEmision1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, 260, 30));

        fechaHoraEmison.setEditable(false);
        fechaHoraEmison.setBackground(new java.awt.Color(255, 255, 255));
        fechaHoraEmison.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        fechaHoraEmison.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fechaHoraEmison.setText("  Fecha y hora de emisión");
        fechaHoraEmison.setBorder(null);
        fechaHoraEmison.setFocusable(false);
        jPanel1.add(fechaHoraEmison, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 260, 30));

        titulo_fechaHoraCertificacion.setEditable(false);
        titulo_fechaHoraCertificacion.setBackground(new java.awt.Color(198, 54, 55));
        titulo_fechaHoraCertificacion.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_fechaHoraCertificacion.setForeground(new java.awt.Color(255, 255, 255));
        titulo_fechaHoraCertificacion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        titulo_fechaHoraCertificacion.setText("  Fecha y hora de certificación");
        titulo_fechaHoraCertificacion.setBorder(null);
        titulo_fechaHoraCertificacion.setFocusable(false);
        jPanel1.add(titulo_fechaHoraCertificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 260, 30));

        titulo_codigoPostalExped1.setEditable(false);
        titulo_codigoPostalExped1.setBackground(new java.awt.Color(198, 54, 55));
        titulo_codigoPostalExped1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_codigoPostalExped1.setForeground(new java.awt.Color(255, 255, 255));
        titulo_codigoPostalExped1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        titulo_codigoPostalExped1.setText("  Codigo postal de expedición");
        titulo_codigoPostalExped1.setBorder(null);
        titulo_codigoPostalExped1.setFocusable(false);
        jPanel1.add(titulo_codigoPostalExped1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 260, 30));

        cp_Expedicion1.setEditable(false);
        cp_Expedicion1.setBackground(new java.awt.Color(255, 255, 255));
        cp_Expedicion1.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        cp_Expedicion1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        cp_Expedicion1.setText("  Fecha y hora de emisión");
        cp_Expedicion1.setBorder(null);
        cp_Expedicion1.setFocusable(false);
        jPanel1.add(cp_Expedicion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 260, 30));

        encabezado_Receptor.setBackground(new java.awt.Color(198, 54, 55));
        encabezado_Receptor.setRoundTopLeft(20);
        encabezado_Receptor.setRoundTopRight(20);
        encabezado_Receptor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receptor");
        encabezado_Receptor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 440, 40));

        jPanel1.add(encabezado_Receptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 490, 40));

        encabezado_datosFiscales.setBackground(new java.awt.Color(198, 54, 55));
        encabezado_datosFiscales.setRoundTopLeft(20);
        encabezado_datosFiscales.setRoundTopRight(20);
        encabezado_datosFiscales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Datos Fiscales");
        encabezado_datosFiscales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 370, 40));

        jPanel1.add(encabezado_datosFiscales, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 490, 40));

        contenedor_receptor.setBackground(new java.awt.Color(255, 255, 255));
        contenedor_receptor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 54, 55), 2, true));
        contenedor_receptor.setRoundBottomLeft(20);
        contenedor_receptor.setRoundBottomRight(20);
        contenedor_receptor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre_padre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        nombre_padre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombre_padre.setText("Angel Ramirez Castro");
        contenedor_receptor.add(nombre_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 460, 50));

        Tituloregimen_padre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Tituloregimen_padre.setText("Regimen Fiscal:");
        contenedor_receptor.add(Tituloregimen_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, 30));

        domicilio_fiscalPadre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        domicilio_fiscalPadre.setText("39890");
        contenedor_receptor.add(domicilio_fiscalPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 330, 30));

        rfc_padre1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rfc_padre1.setText("RACA031202FDD");
        contenedor_receptor.add(rfc_padre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 330, 30));

        titulo_cfdi1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_cfdi1.setText("Uso CDFI:");
        contenedor_receptor.add(titulo_cfdi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        titulo_cp2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_cp2.setText("Domicilio:");
        contenedor_receptor.add(titulo_cp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        regimen_padre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        regimen_padre.setText("jLabel4");
        contenedor_receptor.add(regimen_padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 330, 50));

        titulo_rfc2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_rfc2.setText("RFC:");
        contenedor_receptor.add(titulo_rfc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 30));

        uso_CFDI2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        uso_CFDI2.setText("D10 Pagos por servicios educativos (Colegiatura)");
        contenedor_receptor.add(uso_CFDI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 330, 30));

        jPanel1.add(contenedor_receptor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 490, 250));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 1070, -1, -1));

        contenedor_datosFiscales.setBackground(new java.awt.Color(255, 255, 255));
        contenedor_datosFiscales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(198, 54, 55), 2, true));
        contenedor_datosFiscales.setRoundBottomLeft(20);
        contenedor_datosFiscales.setRoundBottomRight(20);
        contenedor_datosFiscales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_certificadoEmisor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_certificadoEmisor.setText("Numero serie del certificado SAT:");
        contenedor_datosFiscales.add(titulo_certificadoEmisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 30));

        certificadoSAT.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        certificadoSAT.setText("JHHUIBJ2WED8IHJP9DWNJKnjiecuinewuihwsnjiwxnjiowsnj");
        contenedor_datosFiscales.add(certificadoSAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 470, 30));

        titulo_exportación.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_exportación.setText("Exportación:");
        contenedor_datosFiscales.add(titulo_exportación, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, 30));

        folioSat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        folioSat.setText("JHHUIBJ2WED8IHJP9DWNJKnjiecuinewuihwsnjiwxnjiowsnj");
        contenedor_datosFiscales.add(folioSat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 470, 30));

        titulo_certificadoEmisor1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_certificadoEmisor1.setText("Numero de serie certificado emisor:");
        contenedor_datosFiscales.add(titulo_certificadoEmisor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 30));

        exportacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        exportacion.setText("No aplica");
        contenedor_datosFiscales.add(exportacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 90, 30));

        titulo_FolioSat2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_FolioSat2.setText("Folio SAT:");
        contenedor_datosFiscales.add(titulo_FolioSat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        titulo_leyenda.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        titulo_leyenda.setText("Leyenda:");
        contenedor_datosFiscales.add(titulo_leyenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, 30));

        certificadoEmisor2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        certificadoEmisor2.setText("JHHUIBJ2WED8IHJP9DWNJKnjiecuinewuihwsnjiwxnjiowsnj");
        contenedor_datosFiscales.add(certificadoEmisor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 470, 30));

        jPanel1.add(contenedor_datosFiscales, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 490, 250));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1094, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloFactura(null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tituloregimen_padre;
    private javax.swing.JLabel certificadoEmisor2;
    private javax.swing.JLabel certificadoSAT;
    private paneles.PanelRound contenedor_datosFiscales;
    private paneles.PanelRound contenedor_receptor;
    private javax.swing.JTextField cp_Expedicion1;
    private javax.swing.JLabel domicilio_fiscalPadre;
    private paneles.PanelRound encabezado_Receptor;
    private paneles.PanelRound encabezado_datosFiscales;
    private javax.swing.JLabel exportacion;
    private javax.swing.JTextField fechaHoraEmision;
    private javax.swing.JTextField fechaHoraEmison;
    private javax.swing.JLabel folioSat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo_lb;
    private javax.swing.JLabel no_factura;
    private javax.swing.JLabel nombre_emisor;
    private javax.swing.JLabel nombre_escuela;
    private javax.swing.JLabel nombre_escuela1;
    private javax.swing.JLabel nombre_padre;
    private javax.swing.JLabel regimen_padre;
    private javax.swing.JLabel rfc_emisor;
    private javax.swing.JLabel rfc_emisor1;
    private javax.swing.JLabel rfc_padre1;
    private javax.swing.JLabel titulo_FolioSat2;
    private javax.swing.JLabel titulo_certificadoEmisor;
    private javax.swing.JLabel titulo_certificadoEmisor1;
    private javax.swing.JLabel titulo_cfdi1;
    private javax.swing.JTextField titulo_codigoPostalExped1;
    private javax.swing.JLabel titulo_cp2;
    private javax.swing.JLabel titulo_exportación;
    private javax.swing.JTextField titulo_fechaHoraCertificacion;
    private javax.swing.JTextField titulo_fechaHoraEmision1;
    private javax.swing.JLabel titulo_leyenda;
    private javax.swing.JLabel titulo_rfc2;
    private javax.swing.JLabel uso_CFDI2;
    // End of variables declaration//GEN-END:variables
}
